spring.application.name=planetic

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/planetic
spring.datasource.username=root
spring.datasource.password=test1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ssim87029@gmail.com
spring.mail.password=iwgo iycb ccru bukp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini